/**
 * lib/utils/students/mappers.ts
 *
 * Data-mapping functions for the students domain.
 * No React, no Supabase, no UI logic.
 * All null/undefined cases handled explicitly.
 */

import type { Students, StudentRaw } from '@/lib/types/admin/students/student.types'
import type { StudentFormData, StudentPayload } from '@/lib/types/admin/students/student.types'

/**
 * Maps a raw Supabase joined row (`StudentRaw`) to the flat `Student` display
 * shape used throughout the UI.
 *
 * Handles:
 *  - Null profiles (defensive — `!inner` guarantees presence at DB level)
 *  - Null program join (LEFT join — student may have no program)
 *  - All nullable student columns
 */
export function mapStudentRow(row: StudentRaw): Students {
  return {
    id:           row.id,
    full_name:    row.profiles.full_name ?? null,
    email:        row.profiles.email,
    student_id:   row.student_id,
    year_level:   row.year_level,
    created_at:   row.created_at,
    program_id:   row.program_id,
    program_code: row.programs?.code ?? null,
    program_name: row.programs?.name ?? null,
  }
}

export function mapFormToPayload(form: StudentFormData): StudentPayload {
  return {
    id: '', // ID will be generated by the supabase
    student_id: form.student_id,
    year_level: form.year_level,
    program_id: form.program_id,
    school: form.school,        // add if your form collects school
  }
}